language: php

php:
    - 5.4

before_script:
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update
  - /home/travis/.phpenv/versions/5.5/bin/composer install --dev

script:
  - phpunit -c app
